"""your message

Revision ID: 3f3dc63d2fe7
Revises: 03e0883344af
Create Date: 2024-05-14 20:25:22.742997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3dc63d2fe7'
down_revision = '03e0883344af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
